apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rhoai-keycloak.fullname" . }}-sync
  labels:
    app.kubernetes.io/name: {{ include "rhoai-keycloak.name" . }}-sync
    helm.sh/chart: {{ include "rhoai-keycloak.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rhoai-keycloak.name" . }}-sync
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rhoai-keycloak.name" . }}-sync
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # place this pod on each host w/ a keycloak server
      # and a sync pod doesn't already exist
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "rhoai-keycloak.name" . }}-sync
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - keycloak
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.sync.awsAccessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.sync.awsSecretAccessKey }}
            - name: S3_BUCKET
              value: {{ .Values.sync.s3Bucket }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: theme
              mountPath: /opt/jboss/keycloak/themes
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: theme
          hostPath:
            path: /data/keycloak-themes
      imagePullSecrets:
        - name: rhoaidev
