# Default values for rhoai-keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: rhoai/keycloak-theme-sync
  tag: dev
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

sync:
  awsAccessKeyId: 
  awsSecretAccessKey: 
  s3Bucket: temp-rho-theme

keycloak:
  keycloak:
    replicas: 2
    username: keycloak
    password: keycloak

    persistence:
      deployPostgres: false
      dbVendor: h2
      dbName: keycloak
      dbHost: localhost
      dbPort: 3306 
      dbUser: keycloak
      dbPassword: keycloak

    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/mytheme

    extraVolumes: |
      - name: theme
        hostPath:
          path: /data/keycloak

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
